-include myphp_ext_tanafaat.dep
myphp_ext_tanafaat.lo: /Users/mac/Desktop/myphp_ext_tanafaat/myphp_ext_tanafaat.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mac/Desktop/myphp_ext_tanafaat $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mac/Desktop/myphp_ext_tanafaat/myphp_ext_tanafaat.c -o myphp_ext_tanafaat.lo  -MMD -MF myphp_ext_tanafaat.dep -MT myphp_ext_tanafaat.lo
$(phplibdir)/myphp_ext_tanafaat.la: ./myphp_ext_tanafaat.la
	$(LIBTOOL) --tag=CC --mode=install cp ./myphp_ext_tanafaat.la $(phplibdir)

./myphp_ext_tanafaat.la: $(shared_objects_myphp_ext_tanafaat) $(MYPHP_EXT_TANAFAAT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_myphp_ext_tanafaat) $(MYPHP_EXT_TANAFAAT_SHARED_LIBADD)

